[package]
name = "gz_cleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
serde_json = "1.0"
rayon = "1.10"
crossbeam-channel = "0.5"

[profile.release]
opt-level = 3
lto = true
