[package]
name = "parquet_generator"
version = "0.1.0"
edition = "2024"

[dependencies]

flate2 = "1.0"
serde_json = "1.0"
chrono = "=0.4"
duckdb = { version = "1.4.3", features = ["bundled"] }
rayon = "1.10"
crossbeam-channel = "0.5"
