[package]
name = "gz_to_parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
serde_json = "1.0"
duckdb = { version = "1.4.3", features = ["bundled"] }
crossbeam-channel = "0.5"

[profile.release]
opt-level = 3
lto = true
